import {
  IconRefresh,
  IconShieldCheck,
  IconAlertTriangle,
  IconSearch,
  IconBrain,
  IconChartBar,
  IconUsers,
  IconClipboardCheck,
  IconFileAnalytics,
  IconNetwork,
  IconEye,
  IconBulb,
  IconArrowRight,
  IconCircleCheck,
  IconListDetails,
  IconMessage,
  IconSchool,
  IconActivity,
  IconTargetArrow,
  IconScale,
  IconGavel,
  IconTrendingUp,
  IconTrendingDown,
  IconMoodSad,
  IconMoodHappy,
  IconReportAnalytics,
  IconSettings,
  IconClockHour4,
  IconStar,
  type Icon,
} from "@tabler/icons-react";

const iconMap: Record<string, Icon> = {
  refresh: IconRefresh,
  "shield-check": IconShieldCheck,
  "alert-triangle": IconAlertTriangle,
  search: IconSearch,
  brain: IconBrain,
  "chart-bar": IconChartBar,
  users: IconUsers,
  "clipboard-check": IconClipboardCheck,
  "file-analytics": IconFileAnalytics,
  network: IconNetwork,
  eye: IconEye,
  bulb: IconBulb,
  "arrow-right": IconArrowRight,
  "circle-check": IconCircleCheck,
  "list-details": IconListDetails,
  message: IconMessage,
  school: IconSchool,
  activity: IconActivity,
  "target-arrow": IconTargetArrow,
  scale: IconScale,
  gavel: IconGavel,
  "trending-up": IconTrendingUp,
  "trending-down": IconTrendingDown,
  "mood-sad": IconMoodSad,
  "mood-happy": IconMoodHappy,
  "report-analytics": IconReportAnalytics,
  settings: IconSettings,
  "clock-hour-4": IconClockHour4,
  star: IconStar,
};

export function resolveIcon(name: string): Icon {
  return iconMap[name] ?? IconBulb;
}
