"use client";

import {
  Card,
  CardContent,
  CardDescription,
  CardHeader,
  CardTitle,
} from "@/components/ui/card";
import { ScrollArea } from "@/components/ui/scroll-area";
import { IconCpu } from "@tabler/icons-react";

interface ActivityItem {
  id: number;
  action: string;
  details: string;
  time: string;
  module: string;
}

export function ActivityStream({ activities }: { activities: ActivityItem[] }) {
  return (
    <Card className="col-span-3">
      <CardHeader>
        <CardTitle>AI Activity Stream</CardTitle>
        <CardDescription>
          Recent automated actions and insights generated by the system.
        </CardDescription>
      </CardHeader>
      <CardContent>
        <ScrollArea className="h-[350px] pr-4">
          <div className="space-y-6">
            {activities.map((item) => (
              <div key={item.id} className="flex gap-4">
                <div className="mt-1 flex h-9 w-9 shrink-0 items-center justify-center rounded-full bg-primary/10 text-primary">
                  <IconCpu className="h-5 w-5" />
                </div>
                <div className="space-y-1">
                  <p className="text-sm font-medium leading-none">
                    {item.action}
                  </p>
                  <p className="text-sm text-muted-foreground">
                    {item.details}
                  </p>
                  <div className="flex items-center pt-1 text-xs text-muted-foreground">
                    <span className="font-semibold text-primary/80 mr-2">
                      {item.module}
                    </span>
                    <span>{item.time}</span>
                  </div>
                </div>
              </div>
            ))}
          </div>
        </ScrollArea>
      </CardContent>
    </Card>
  );
}
