/**
 * Build SQL seed files from generated content (seed-content.json).
 *
 * Usage: bun run scripts/build-seed-sql.ts
 *
 * Input:  scripts/seed-content.json
 * Output: init/postgres/04_wovo_new_seed.sql
 *         init/sqlserver/02_seed_data.sql
 *         init/mysql/02_seed_data.sql
 */

import { readFileSync, writeFileSync } from "fs";
import { join } from "path";
import { randomUUID } from "crypto";

const SCRIPT_DIR = import.meta.dir;
const ROOT_DIR = join(SCRIPT_DIR, "..");

interface SeedContent {
  factoryNames: string[];
  workerFirstNames: string[];
  workerLastNames: string[];
  grievanceMessages: Record<string, string[]>;
  surveyQuestionTitles: string[];
  surveyScoreOptionSets: Array<{ options: Array<{ label: string; weight: number }> }>;
  surveyFreeTextResponses: string[];
  coursesByCategory: Record<string, Array<{ name: string; summary: string }>>;
}

const content: SeedContent = JSON.parse(
  readFileSync(join(SCRIPT_DIR, "seed-content.json"), "utf-8"),
);

// ─── Shared constants ──────────────────────────────────────

const SUPPLIER_COUNT = 200;
const WORKER_COUNT = 50000;
const SURVEY_COUNT = 500;
const QUESTIONS_PER_SURVEY = 10;
const CASE_COUNT = 5000;
const ENROLLMENT_COUNT = 20000;

const COUNTRIES = [
  { name: "Vietnam", weight: 30 },
  { name: "Bangladesh", weight: 20 },
  { name: "Cambodia", weight: 15 },
  { name: "China", weight: 10 },
  { name: "India", weight: 10 },
  { name: "Indonesia", weight: 5 },
  { name: "Thailand", weight: 3 },
  { name: "Myanmar", weight: 2 },
  { name: "Ethiopia", weight: 2 },
  { name: "Sri Lanka", weight: 1 },
  { name: "Pakistan", weight: 1 },
  { name: "Philippines", weight: 1 },
];

const CASE_TYPES = [
  "Harassment",
  "Wage Theft",
  "Safety Violation",
  "Forced Labor",
  "Child Labor",
  "Discrimination",
  "Working Hours Violation",
  "Environmental Violation",
];

// Deterministic seeded random
let _seed = 42;
function seededRandom(): number {
  _seed = (_seed * 16807 + 0) % 2147483647;
  return (_seed - 1) / 2147483646;
}
function randInt(min: number, max: number): number {
  return Math.floor(seededRandom() * (max - min + 1)) + min;
}
function pick<T>(arr: T[]): T {
  return arr[Math.floor(seededRandom() * arr.length)];
}
function esc(s: string): string {
  return s.replace(/'/g, "''");
}

function isoDate(d: Date): string {
  return d.toISOString().slice(0, 19).replace("T", " ");
}

function randomDate(daysBack: number): Date {
  const d = new Date();
  d.setDate(d.getDate() - randInt(0, daysBack));
  d.setHours(randInt(0, 23), randInt(0, 59), randInt(0, 59));
  return d;
}

// Distribute N items with Pareto-like distribution across M buckets
function paretoDistribution(totalItems: number, buckets: number, skew: number = 0.8): number[] {
  const result = new Array(buckets).fill(0);
  for (let i = 0; i < totalItems; i++) {
    // Power-law: early buckets get more items
    const r = seededRandom();
    const bucket = Math.floor(Math.pow(r, 1 / (1 - skew)) * buckets) % buckets;
    result[bucket]++;
  }
  return result;
}

// Assign countries to suppliers using weights
function assignCountries(): string[] {
  const countries: string[] = [];
  for (const c of COUNTRIES) {
    const count = Math.round((c.weight / 100) * SUPPLIER_COUNT);
    for (let i = 0; i < count; i++) countries.push(c.name);
  }
  while (countries.length < SUPPLIER_COUNT) countries.push(pick(COUNTRIES).name);
  while (countries.length > SUPPLIER_COUNT) countries.pop();
  // Shuffle
  return countries.sort(() => seededRandom() - 0.5);
}

// ═══════════════════════════════════════════════════════════
// PostgreSQL Seed
// ═══════════════════════════════════════════════════════════

function buildPostgresSeed(): string {
  const lines: string[] = [];
  lines.push("-- Auto-generated seed data for PostgreSQL databases");
  lines.push("-- Generated by scripts/build-seed-sql.ts");
  lines.push("");

  const supplierCountries = assignCountries();
  const factoryNames = content.factoryNames.length >= SUPPLIER_COUNT
    ? content.factoryNames
    : [...content.factoryNames, ...Array.from({ length: SUPPLIER_COUNT - content.factoryNames.length }, (_, i) => `Factory ${i + 201}`)];

  // ═══════════════════════════════════════════════════════════
  // wc_global: Workers (mdl_participant)
  // ═══════════════════════════════════════════════════════════
  lines.push("\\connect wc_global");
  lines.push("");
  lines.push("BEGIN;");
  lines.push("");

  // ── mdl_participant (workers) ──
  lines.push("-- Workers (mdl_participant) in wc_global");
  const firstNames = content.workerFirstNames.length > 0 ? content.workerFirstNames : Array.from({ length: 100 }, (_, i) => `Worker${i}`);
  const lastNames = content.workerLastNames.length > 0 ? content.workerLastNames : Array.from({ length: 50 }, (_, i) => `Last${i}`);

  // Power-law distribution of workers across suppliers
  const workerDistrib = paretoDistribution(WORKER_COUNT, SUPPLIER_COUNT, 0.7);

  let workerId = 1;
  const WORKER_BATCH = 500;
  let batchValues: string[] = [];

  for (let s = 0; s < SUPPLIER_COUNT; s++) {
    const supplierId = s + 1;
    const count = Math.max(10, workerDistrib[s]);

    for (let w = 0; w < count && workerId <= WORKER_COUNT; w++) {
      const fn = esc(pick(firstNames));
      const ln = esc(pick(lastNames));
      const gender = seededRandom() < 0.6 ? 1 : 2;
      const startDate = isoDate(randomDate(1095));
      const identifier = `W${String(workerId).padStart(6, "0")}`;
      const phone = `+${randInt(1, 99)}${String(randInt(100000000, 999999999))}`;

      batchValues.push(
        `(${workerId}, ${supplierId}, '${fn}', '${ln}', '${fn} ${ln}', '${fn} ${ln}', '${identifier}', true, false, false, ${gender}, '${startDate}', '${phone}')`,
      );

      if (batchValues.length >= WORKER_BATCH) {
        lines.push(
          `INSERT INTO mdl_participant (id, client_id, first_name, last_name, full_name, clean_full_name, identifier, is_active, is_transfer, is_deleted, gender_id, worker_start_date, phone_number) VALUES\n${batchValues.join(",\n")};`,
        );
        batchValues = [];
      }
      workerId++;
    }
  }
  if (batchValues.length > 0) {
    lines.push(
      `INSERT INTO mdl_participant (id, client_id, first_name, last_name, full_name, clean_full_name, identifier, is_active, is_transfer, is_deleted, gender_id, worker_start_date, phone_number) VALUES\n${batchValues.join(",\n")};`,
    );
  }
  lines.push(`SELECT setval('mdl_participant_id_seq', ${workerId - 1}, true);`);
  lines.push("");
  lines.push("COMMIT;");
  lines.push("");

  // ═══════════════════════════════════════════════════════════
  // wovo_new: Suppliers, Surveys, Responses
  // ═══════════════════════════════════════════════════════════
  lines.push("\\connect wovo_new");
  lines.push("");
  lines.push("BEGIN;");
  lines.push("");

  // ── Prerequisite: supported languages (FK target for survey responses) ──
  lines.push("-- Supported languages (FK prerequisite)");
  lines.push(`INSERT INTO translations_mdlsupportedlanguages (id, name, language_code, is_active, is_ui_language, is_translated, resource_version, is_app_supported, wovo_language_id, created_date, modified_date) VALUES`);
  lines.push(`  (1, 'English', 'en', true, true, true, 1.0, true, 1, NOW(), NOW()),`);
  lines.push(`  (2, 'Vietnamese', 'vi', true, true, true, 1.0, true, 2, NOW(), NOW()),`);
  lines.push(`  (3, 'Bengali', 'bn', true, true, true, 1.0, true, 3, NOW(), NOW()),`);
  lines.push(`  (4, 'Khmer', 'km', true, true, true, 1.0, true, 4, NOW(), NOW()),`);
  lines.push(`  (5, 'Chinese', 'zh', true, true, true, 1.0, true, 5, NOW(), NOW()),`);
  lines.push(`  (6, 'Hindi', 'hi', true, true, true, 1.0, true, 6, NOW(), NOW()),`);
  lines.push(`  (7, 'Indonesian', 'id', true, true, true, 1.0, true, 7, NOW(), NOW()),`);
  lines.push(`  (8, 'Thai', 'th', true, true, true, 1.0, true, 8, NOW(), NOW()),`);
  lines.push(`  (9, 'Burmese', 'my', true, true, true, 1.0, true, 9, NOW(), NOW()),`);
  lines.push(`  (10, 'Amharic', 'am', true, true, true, 1.0, true, 10, NOW(), NOW());`);
  lines.push(`SELECT setval(pg_get_serial_sequence('translations_mdlsupportedlanguages', 'id'), 10, true);`);
  lines.push("");

  // ── clients_clientinfo ──
  lines.push("-- Suppliers (clients_clientinfo)");
  for (let i = 1; i <= SUPPLIER_COUNT; i++) {
    const name = esc(factoryNames[i - 1]);
    const country = supplierCountries[i - 1];
    const created = isoDate(randomDate(730));
    lines.push(
      `INSERT INTO clients_clientinfo (id, name, client_key, client_id, country, is_active, is_deleted, is_anonymous, allow_connect_raw_data_download, allow_survey_raw_data_download, allow_questionnaire_raw_data_download, created_at, created_date) VALUES (${i}, '${name}', ${i}, 'supplier-${String(i).padStart(3, "0")}', '${country}', true, false, false, false, false, false, '${created}', '${created}');`,
    );
  }
  lines.push(`SELECT setval('clients_clientinfo_id_seq', ${SUPPLIER_COUNT}, true);`);
  lines.push("");

  // ── survey_mdlsurveyquestiontype ──
  lines.push("-- Survey question types");
  const qtypes = [
    { name: "Scored", question_type: 1, dic_key: "scored" },
    { name: "Single Select", question_type: 2, dic_key: "single_select" },
    { name: "Multi Select", question_type: 3, dic_key: "multi_select" },
    { name: "Free Text", question_type: 4, dic_key: "free_text" },
  ];
  const qtypeUuids: string[] = [];
  for (const qt of qtypes) {
    const uuid = randomUUID();
    qtypeUuids.push(uuid);
    lines.push(
      `INSERT INTO survey_mdlsurveyquestiontype (id, name, question_type, is_active, dic_key) VALUES ('${uuid}', '${qt.name}', ${qt.question_type}, true, '${qt.dic_key}');`,
    );
  }
  lines.push("");

  // ── surveys + questions + options + responses ──
  lines.push("-- Surveys, questions, options, and responses");

  const surveyQuestions = content.surveyQuestionTitles.length > 0
    ? content.surveyQuestionTitles
    : Array.from({ length: 50 }, (_, i) => `Survey Question ${i + 1}`);

  const optionSets = content.surveyScoreOptionSets.length > 0
    ? content.surveyScoreOptionSets
    : [{ options: [{ label: "Good", weight: 100 }, { label: "Fair", weight: 50 }, { label: "Poor", weight: 25 }] }];

  const freeTextResponses = content.surveyFreeTextResponses.length > 0
    ? content.surveyFreeTextResponses
    : ["No comment.", "Everything is fine.", "Need improvement."];

  let surveyQuestionJunctionId = 1;
  let questionOptionJunctionId = 1;
  let userResponseCount = 0;
  let questionResponseCount = 0;

  // Batch collections for bulk insert
  const surveyInserts: string[] = [];
  const questionInserts: string[] = [];
  const optionInserts: string[] = [];
  const sqJunctionInserts: string[] = [];
  const qoJunctionInserts: string[] = [];
  const userResponseInserts: string[] = [];
  const questionResponseInserts: string[] = [];

  for (let s = 0; s < SURVEY_COUNT; s++) {
    const surveyId = randomUUID();
    const supplierId = (s % SUPPLIER_COUNT) + 1;
    const statusRoll = seededRandom();
    const status = statusRoll < 0.3 ? 1 : statusRoll < 0.9 ? 2 : 0; // active, closed, draft
    const fromDate = randomDate(730);
    const toDate = new Date(fromDate);
    toDate.setDate(toDate.getDate() + randInt(14, 60));
    const surveyName = esc(pick(surveyQuestions) + ` - ${fromDate.getFullYear()} Q${Math.ceil((fromDate.getMonth() + 1) / 3)}`);

    surveyInserts.push(
      `('${surveyId}', ${supplierId}, '${surveyName}', '${isoDate(fromDate)}', '${isoDate(toDate)}', ${status}, 1, ${s + 1}, false, false, false, false, false, '${isoDate(fromDate)}')`,
    );

    // Questions for this survey
    const questionIds: string[] = [];
    const questionOptionIds: Map<string, string[]> = new Map();

    for (let q = 0; q < QUESTIONS_PER_SURVEY; q++) {
      const questionId = randomUUID();
      questionIds.push(questionId);

      // 60% scored, 10% single, 10% multi, 20% free text
      const typeRoll = seededRandom();
      let typeIdx: number;
      if (typeRoll < 0.6) typeIdx = 0;       // scored
      else if (typeRoll < 0.7) typeIdx = 1;   // single
      else if (typeRoll < 0.8) typeIdx = 2;   // multi
      else typeIdx = 3;                        // free text

      const questionTitle = esc(surveyQuestions[(s * QUESTIONS_PER_SURVEY + q) % surveyQuestions.length]);

      questionInserts.push(
        `('${questionId}', ${supplierId}, '${questionTitle}', true, true, false, true, true, false, ${q + 1}, '${qtypeUuids[typeIdx]}', '${isoDate(fromDate)}')`,
      );

      sqJunctionInserts.push(
        `(${surveyQuestionJunctionId++}, '${surveyId}', '${questionId}')`,
      );

      // Options for non-free-text questions
      const optIds: string[] = [];
      if (typeIdx < 3) {
        const optSet = optionSets[q % optionSets.length];
        for (const opt of optSet.options) {
          const optId = randomUUID();
          optIds.push(optId);
          const weight = typeIdx === 0 ? String(opt.weight) : "0";
          optionInserts.push(
            `('${optId}', ${supplierId}, '${esc(opt.label)}', '${weight}', false, '', '${isoDate(fromDate)}')`,
          );
          qoJunctionInserts.push(
            `(${questionOptionJunctionId++}, '${questionId}', '${optId}')`,
          );
        }
      }
      questionOptionIds.set(questionId, optIds);
    }

    // User responses (50-150 per survey for completed/active surveys)
    if (status > 0) { // active or closed
      const responseCount = randInt(50, 150);
      for (let r = 0; r < responseCount && userResponseCount < 50000; r++) {
        const userId = randInt(1, WORKER_COUNT);
        const urId = randomUUID();
        const gender = seededRandom() < 0.6 ? 1 : 2;
        const age = randInt(18, 55);
        const tenure = randInt(1, 120); // months
        const ageLabel = age < 25 ? "18-24" : age < 35 ? "25-34" : age < 45 ? "35-44" : "45+";
        const tenureLabel = tenure < 12 ? "< 1 year" : tenure < 36 ? "1-3 years" : "3+ years";
        const country = supplierCountries[supplierId - 1];

        userResponseInserts.push(
          `('${urId}', ${supplierId}, ${userId}, 1, 1, 1, 0, '${country}', ${gender}, ${age}, ${tenure}, '${ageLabel}', '${tenureLabel}', 'W${String(userId).padStart(6, "0")}', '${esc(country)}', 0, 0, 1, '${surveyId}', '${isoDate(fromDate)}')`,
        );
        userResponseCount++;

        // Answer each question
        for (let q = 0; q < questionIds.length && questionResponseCount < 250000; q++) {
          if (seededRandom() < 0.1) continue; // 10% skip rate

          const qId = questionIds[q];
          const optIds = questionOptionIds.get(qId) || [];
          const qrId = randomUUID();
          let textResponse: string;
          let optionId: string;

          if (optIds.length > 0) {
            // Select an option (weighted toward higher scores for realism)
            const idx = Math.min(optIds.length - 1, Math.floor(Math.pow(seededRandom(), 1.5) * optIds.length));
            optionId = optIds[idx];
            textResponse = "";
          } else {
            // Free text
            optionId = "";
            textResponse = esc(pick(freeTextResponses));
          }

          questionResponseInserts.push(
            `('${qrId}', ${supplierId}, '${esc(textResponse)}', ${optionId ? `'${optionId}'` : "NULL"}, '${surveyId}', '${qId}', '${urId}', '${isoDate(fromDate)}')`,
          );
          questionResponseCount++;
        }
      }
    }
  }

  // Write surveys
  const BATCH = 200;
  for (let i = 0; i < surveyInserts.length; i += BATCH) {
    lines.push(
      `INSERT INTO survey_mdlsurvey (id, client_id, name, from_date, to_date, status, source, sequence_id, is_locked, is_anonymous, is_clients_disabled, one_response_per_device, is_randomize, created_date) VALUES\n${surveyInserts.slice(i, i + BATCH).join(",\n")};`,
    );
  }
  lines.push("");

  // Write questions
  for (let i = 0; i < questionInserts.length; i += BATCH) {
    lines.push(
      `INSERT INTO survey_mdlsurveyquestions (id, client_id, title, is_active, is_accessible, is_deleted, is_mandatory, is_locked, is_emoji_enabled, sequence_id, q_type_id, created_date) VALUES\n${questionInserts.slice(i, i + BATCH).join(",\n")};`,
    );
  }
  lines.push("");

  // Write options
  for (let i = 0; i < optionInserts.length; i += BATCH) {
    lines.push(
      `INSERT INTO survey_mdlsurveyquestionoptions (id, client_id, label, weight, is_cna, icon_class, created_date) VALUES\n${optionInserts.slice(i, i + BATCH).join(",\n")};`,
    );
  }
  lines.push("");

  // Write survey-question junction
  for (let i = 0; i < sqJunctionInserts.length; i += BATCH) {
    lines.push(
      `INSERT INTO survey_mdlsurvey_questions (id, mdlsurvey_id, mdlsurveyquestions_id) VALUES\n${sqJunctionInserts.slice(i, i + BATCH).join(",\n")};`,
    );
  }
  lines.push("");

  // Write question-option junction
  for (let i = 0; i < qoJunctionInserts.length; i += BATCH) {
    lines.push(
      `INSERT INTO survey_mdlsurveyquestions_question_options (id, mdlsurveyquestions_id, mdlsurveyquestionoptions_id) VALUES\n${qoJunctionInserts.slice(i, i + BATCH).join(",\n")};`,
    );
  }
  lines.push("");

  // Write user responses
  for (let i = 0; i < userResponseInserts.length; i += BATCH) {
    lines.push(
      `INSERT INTO survey_mdlsurveyuserresponses (id, client_id, user_id, is_completed, response_type, response_source, randomise_status, country, gender, age, tenure, age_label, tenure_label, identifier, dept_name, smart_phone, job_role, language_id, survey_id_id, created_date) VALUES\n${userResponseInserts.slice(i, i + BATCH).join(",\n")};`,
    );
  }
  lines.push("");

  // Write question responses
  for (let i = 0; i < questionResponseInserts.length; i += BATCH) {
    lines.push(
      `INSERT INTO survey_mdlsurveyquestionresponses (id, client_id, text_response, question_option_id, survey_id, survey_question_id, survey_user_response_id, created_date) VALUES\n${questionResponseInserts.slice(i, i + BATCH).join(",\n")};`,
    );
  }
  lines.push("");

  // Reset sequences
  lines.push(`SELECT setval('survey_mdlsurvey_questions_id_seq', ${surveyQuestionJunctionId}, true);`);
  lines.push(`SELECT setval('survey_mdlsurveyquestions_question_options_id_seq', ${questionOptionJunctionId}, true);`);
  lines.push("");

  lines.push("COMMIT;");
  lines.push("");
  lines.push(`-- Summary: ${SUPPLIER_COUNT} suppliers, ${workerId - 1} workers, ${SURVEY_COUNT} surveys`);
  lines.push(`-- ${questionInserts.length} questions, ${optionInserts.length} options`);
  lines.push(`-- ${userResponseCount} user responses, ${questionResponseCount} question responses`);

  return lines.join("\n");
}

// ═══════════════════════════════════════════════════════════
// SQL Server Seed
// ═══════════════════════════════════════════════════════════

function buildSqlServerSeed(): string {
  const lines: string[] = [];
  lines.push("-- Auto-generated seed data for WOVO (SQL Server)");
  lines.push("-- Generated by scripts/build-seed-sql.ts");
  lines.push("GO");
  lines.push("");

  // ── CultureCode ──
  lines.push("SET IDENTITY_INSERT CultureCode ON;");
  const cultures = [
    { id: 1, key: "en_US" },
    { id: 2, key: "vi" },
    { id: 3, key: "bn" },
    { id: 4, key: "km" },
    { id: 5, key: "zh" },
    { id: 6, key: "hi" },
  ];
  for (const c of cultures) {
    lines.push(
      `INSERT INTO CultureCode (Id, [Key], Deleted, ResourceVersion, AppSupported) VALUES (${c.id}, '${c.key}', 0, 1.0, 1);`,
    );
  }
  lines.push("SET IDENTITY_INSERT CultureCode OFF;");
  lines.push("GO");
  lines.push("");

  // ── CaseStatus ──
  lines.push("SET IDENTITY_INSERT CaseStatus ON;");
  lines.push("INSERT INTO CaseStatus (Id, isActive) VALUES (1, 1);");
  lines.push("INSERT INTO CaseStatus (Id, isActive) VALUES (2, 1);");
  lines.push("INSERT INTO CaseStatus (Id, isActive) VALUES (3, 1);");
  lines.push("SET IDENTITY_INSERT CaseStatus OFF;");
  lines.push("GO");
  lines.push("");

  // ── CaseStatusCultureText ──
  lines.push("SET IDENTITY_INSERT CaseStatusCultureText ON;");
  lines.push("INSERT INTO CaseStatusCultureText (Id, Name, CaseStatusId, CultureCodeId) VALUES (1, 'Open', 1, 1);");
  lines.push("INSERT INTO CaseStatusCultureText (Id, Name, CaseStatusId, CultureCodeId) VALUES (2, 'In Progress', 2, 1);");
  lines.push("INSERT INTO CaseStatusCultureText (Id, Name, CaseStatusId, CultureCodeId) VALUES (3, 'Resolved', 3, 1);");
  lines.push("SET IDENTITY_INSERT CaseStatusCultureText OFF;");
  lines.push("GO");
  lines.push("");

  // ── CaseType ──
  lines.push("SET IDENTITY_INSERT CaseType ON;");
  for (let i = 0; i < CASE_TYPES.length; i++) {
    lines.push(
      `INSERT INTO CaseType (Id, Deleted, CreatedBy, Created, isGlobal) VALUES (${i + 1}, 0, 1, GETDATE(), 1);`,
    );
  }
  lines.push("SET IDENTITY_INSERT CaseType OFF;");
  lines.push("GO");
  lines.push("");

  // ── CaseTypeCultureText ──
  lines.push("SET IDENTITY_INSERT CaseTypeCultureText ON;");
  for (let i = 0; i < CASE_TYPES.length; i++) {
    lines.push(
      `INSERT INTO CaseTypeCultureText (Id, Name, CaseTypeId, CultureCodeId) VALUES (${i + 1}, '${esc(CASE_TYPES[i])}', ${i + 1}, 1);`,
    );
  }
  lines.push("SET IDENTITY_INSERT CaseTypeCultureText OFF;");
  lines.push("GO");
  lines.push("");

  // ── CommunicationChannel ──
  lines.push("SET IDENTITY_INSERT CommunicationChannel ON;");
  const channels = ["SMS", "Mobile App", "Web", "Hotline", "In Person"];
  for (let i = 0; i < channels.length; i++) {
    lines.push(
      `INSERT INTO CommunicationChannel (Id, Name, Deleted, CreatedBy, Created) VALUES (${i + 1}, '${channels[i]}', 0, 1, GETDATE());`,
    );
  }
  lines.push("SET IDENTITY_INSERT CommunicationChannel OFF;");
  lines.push("GO");
  lines.push("");

  // ── MessageType ──
  lines.push("SET IDENTITY_INSERT MessageType ON;");
  const msgTypes = ["Incoming", "Outgoing", "System"];
  for (let i = 0; i < msgTypes.length; i++) {
    lines.push(
      `INSERT INTO MessageType (Id, isActive) VALUES (${i + 1}, 1);`,
    );
  }
  lines.push("SET IDENTITY_INSERT MessageType OFF;");
  lines.push("GO");
  lines.push("");

  // ── MessageTypeCultureText ──
  lines.push("SET IDENTITY_INSERT MessageTypeCultureText ON;");
  for (let i = 0; i < msgTypes.length; i++) {
    lines.push(
      `INSERT INTO MessageTypeCultureText (Id, Name, MessageTypeId, CultureCodeId) VALUES (${i + 1}, '${msgTypes[i]}', ${i + 1}, 1);`,
    );
  }
  lines.push("SET IDENTITY_INSERT MessageTypeCultureText OFF;");
  lines.push("GO");
  lines.push("");

  // ── PICCategory ──
  lines.push("SET IDENTITY_INSERT PICCategory ON;");
  for (let i = 0; i < CASE_TYPES.length; i++) {
    lines.push(
      `INSERT INTO PICCategory (Id, CaseTypeId, Deleted, CreatedBy, Created, isGlobal) VALUES (${i + 1}, ${i + 1}, 0, 1, GETDATE(), 1);`,
    );
  }
  lines.push("SET IDENTITY_INSERT PICCategory OFF;");
  lines.push("GO");
  lines.push("");

  // ── Company ──
  lines.push("SET IDENTITY_INSERT Company ON;");
  const supplierCountries = assignCountries();
  const factoryNames = content.factoryNames.length >= SUPPLIER_COUNT
    ? content.factoryNames
    : [...content.factoryNames, ...Array.from({ length: SUPPLIER_COUNT - content.factoryNames.length }, (_, i) => `Factory ${i + 201}`)];

  for (let i = 0; i < SUPPLIER_COUNT; i++) {
    const name = esc(factoryNames[i]);
    const country = supplierCountries[i];
    lines.push(
      `INSERT INTO Company (Id, Name, Deleted, CreatedBy, Created, CleanName, MailingCountry) VALUES (${i + 1}, N'${name}', 0, 1, GETDATE(), N'${name}', N'${country}');`,
    );
  }
  lines.push("SET IDENTITY_INSERT Company OFF;");
  lines.push("GO");
  lines.push("");

  // ── Cases ──
  lines.push("-- Cases (5000)");
  lines.push("SET IDENTITY_INSERT [Case] ON;");

  // Pareto distribution of cases across companies
  const caseDistrib = paretoDistribution(CASE_COUNT, SUPPLIER_COUNT, 0.8);

  // Build all grievance messages as flat array
  const allMessages = Object.values(content.grievanceMessages).flat();
  if (allMessages.length === 0) allMessages.push("Worker complaint reported.");

  let caseId = 1;
  for (let s = 0; s < SUPPLIER_COUNT; s++) {
    const companyId = s + 1;
    const caseCount = caseDistrib[s];

    for (let c = 0; c < caseCount; c++) {
      const statusRoll = seededRandom();
      const statusId = statusRoll < 0.3 ? 1 : statusRoll < 0.6 ? 2 : 3;
      const priorityRoll = seededRandom();
      const priority = priorityRoll < 0.15 ? 1 : priorityRoll < 0.65 ? 2 : 3;
      const caseTypeId = randInt(1, CASE_TYPES.length);
      const created = randomDate(730);
      const createdStr = isoDate(created);
      const resolvedDate = statusId === 3
        ? `'${isoDate(new Date(created.getTime() + randInt(7, 90) * 86400000))}'`
        : "NULL";

      const caseName = esc(`Case #${caseId}: ${CASE_TYPES[caseTypeId - 1]} report`);

      lines.push(
        `INSERT INTO [Case] (Id, Name, CaseStatusId, Priority, CompanyId, CaseTypeId, Deleted, CreatedBy, Created, ResolvedDate, isShowMyDetails) VALUES (${caseId}, N'${caseName}', ${statusId}, ${priority}, ${companyId}, ${caseTypeId}, 0, 1, '${createdStr}', ${resolvedDate}, 0);`,
      );
      caseId++;
    }
  }
  lines.push("SET IDENTITY_INSERT [Case] OFF;");
  lines.push("GO");
  lines.push("");

  // ── Messages ──
  lines.push("-- Messages");
  lines.push("SET IDENTITY_INSERT [Message] ON;");
  let messageId = 1;

  // Reset seed for reproducible case iteration
  _seed = 12345;
  for (let c = 1; c < caseId; c++) {
    const companyId = 1 + ((c - 1) % SUPPLIER_COUNT); // approximate
    const msgCount = randInt(1, 5);
    const caseCreated = randomDate(730);

    for (let m = 0; m < msgCount; m++) {
      const msgTypeId = m === 0 ? 1 : (m % 2 === 0 ? 1 : 2); // first is incoming, alternate
      const channelRoll = seededRandom();
      const channelId = channelRoll < 0.4 ? 2 : channelRoll < 0.7 ? 1 : channelRoll < 0.9 ? 3 : randInt(4, 5);
      const msgDate = new Date(caseCreated.getTime() + m * randInt(1, 14) * 86400000);
      const msgText = esc(pick(allMessages)).substring(0, 1400); // nvarchar(1500) limit

      lines.push(
        `INSERT INTO [Message] (Id, CompanyId, UserId, MessageTypeId, MessageText, ChannelId, Deleted, CreatedBy, Created, CultureCodeId, CaseId) VALUES (${messageId}, ${companyId}, 1, ${msgTypeId}, N'${msgText}', ${channelId}, 0, 1, '${isoDate(msgDate)}', 1, ${c});`,
      );
      messageId++;

      if (messageId > 15000) break;
    }
    if (messageId > 15000) break;
  }
  lines.push("SET IDENTITY_INSERT [Message] OFF;");
  lines.push("GO");
  lines.push("");
  lines.push(`-- Summary: ${SUPPLIER_COUNT} companies, ${caseId - 1} cases, ${messageId - 1} messages`);

  return lines.join("\n");
}

// ═══════════════════════════════════════════════════════════
// MySQL Seed
// ═══════════════════════════════════════════════════════════

function buildMySQLSeed(): string {
  const lines: string[] = [];
  lines.push("-- Auto-generated seed data for iomadprod (Moodle)");
  lines.push("-- Generated by scripts/build-seed-sql.ts");
  lines.push("");
  lines.push("USE iomadprod;");
  lines.push("");

  const allCourses = Object.entries(content.coursesByCategory);

  // ── Course categories ──
  lines.push("-- Course categories");
  for (let i = 0; i < allCourses.length; i++) {
    const [catName] = allCourses[i];
    lines.push(
      `INSERT INTO mdl_course_categories (id, name, sortorder) VALUES (${i + 1}, '${esc(catName)}', ${(i + 1) * 10});`,
    );
  }
  lines.push("");

  // ── Courses ──
  lines.push("-- Courses");
  let courseId = 2; // Moodle reserves id=1 for site course
  const courseIds: number[] = [];

  for (let catIdx = 0; catIdx < allCourses.length; catIdx++) {
    const [, courses] = allCourses[catIdx];
    for (const course of courses) {
      const name = esc(course.name);
      const summary = esc(course.summary);
      const shortname = esc(course.name.substring(0, 30));
      const created = Math.floor(randomDate(730).getTime() / 1000);

      lines.push(
        `INSERT INTO mdl_course (id, category, fullname, shortname, summary, format, visible, enablecompletion, timecreated, timemodified) VALUES (${courseId}, ${catIdx + 1}, '${name}', '${shortname}', '${summary}', 'topics', 1, 1, ${created}, ${created});`,
      );
      courseIds.push(courseId);
      courseId++;
    }
  }
  lines.push("");

  // ── Enrollment methods ──
  lines.push("-- Enrollment methods (one manual per course)");
  let enrolId = 1;
  for (const cId of courseIds) {
    lines.push(
      `INSERT INTO mdl_enrol (id, enrol, status, courseid, timecreated, timemodified) VALUES (${enrolId}, 'manual', 0, ${cId}, UNIX_TIMESTAMP(), UNIX_TIMESTAMP());`,
    );
    enrolId++;
  }
  lines.push("");

  // ── User enrollments ──
  lines.push("-- User enrollments");
  const enrollValues: string[] = [];
  let enrollId = 1;
  const usedPairs = new Set<string>();

  for (let i = 0; i < ENROLLMENT_COUNT; i++) {
    const enrolMethodId = randInt(1, courseIds.length);
    const userId = randInt(1, 5000);
    const key = `${enrolMethodId}:${userId}`;
    if (usedPairs.has(key)) continue;
    usedPairs.add(key);

    const timeStart = Math.floor(randomDate(730).getTime() / 1000);

    enrollValues.push(
      `(${enrollId}, 0, ${enrolMethodId}, ${userId}, ${timeStart}, 2147483647, 0, ${timeStart}, ${timeStart})`,
    );
    enrollId++;

    if (enrollValues.length >= 500) {
      lines.push(
        `INSERT INTO mdl_user_enrolments (id, status, enrolid, userid, timestart, timeend, modifierid, timecreated, timemodified) VALUES\n${enrollValues.join(",\n")};`,
      );
      enrollValues.length = 0;
    }
  }
  if (enrollValues.length > 0) {
    lines.push(
      `INSERT INTO mdl_user_enrolments (id, status, enrolid, userid, timestart, timeend, modifierid, timecreated, timemodified) VALUES\n${enrollValues.join(",\n")};`,
    );
  }
  lines.push("");

  // ── Course completions (~60% rate, varying by "supplier") ──
  lines.push("-- Course completions");
  const completionValues: string[] = [];
  let completionId = 1;
  const usedCompletions = new Set<string>();

  // Varying completion rate per course (20% - 90%)
  const courseCompletionRates = courseIds.map(() => 0.2 + seededRandom() * 0.7);

  for (let i = 0; i < ENROLLMENT_COUNT * 0.8; i++) {
    const courseIdx = randInt(0, courseIds.length - 1);
    const courseIdVal = courseIds[courseIdx];
    const userId = randInt(1, 5000);
    const key = `${userId}:${courseIdVal}`;
    if (usedCompletions.has(key)) continue;

    // Apply per-course completion rate
    if (seededRandom() > courseCompletionRates[courseIdx]) continue;

    usedCompletions.add(key);
    const enrolled = Math.floor(randomDate(730).getTime() / 1000);
    const started = enrolled + randInt(0, 7) * 86400;
    const completed = started + randInt(1, 90) * 86400;

    completionValues.push(
      `(${completionId}, ${userId}, ${courseIdVal}, ${enrolled}, ${started}, ${completed}, 0)`,
    );
    completionId++;

    if (completionValues.length >= 500) {
      lines.push(
        `INSERT INTO mdl_course_completions (id, userid, course, timeenrolled, timestarted, timecompleted, reaggregate) VALUES\n${completionValues.join(",\n")};`,
      );
      completionValues.length = 0;
    }
  }
  if (completionValues.length > 0) {
    lines.push(
      `INSERT INTO mdl_course_completions (id, userid, course, timeenrolled, timestarted, timecompleted, reaggregate) VALUES\n${completionValues.join(",\n")};`,
    );
  }
  lines.push("");
  lines.push(`-- Summary: ${courseIds.length} courses, ${enrollId - 1} enrollments, ${completionId - 1} completions`);

  return lines.join("\n");
}

// ═══════════════════════════════════════════════════════════
// Main
// ═══════════════════════════════════════════════════════════

function main() {
  console.log("🔨 Building SQL seed files from seed-content.json...\n");

  console.log("1/3 PostgreSQL (wovo_new)...");
  const pgSql = buildPostgresSeed();
  const pgPath = join(ROOT_DIR, "init/postgres/04_wovo_new_seed.sql");
  writeFileSync(pgPath, pgSql, "utf-8");
  console.log(`  ✓ ${pgPath} (${(pgSql.length / 1024 / 1024).toFixed(1)} MB)\n`);

  console.log("2/3 SQL Server (WOVO)...");
  const msSql = buildSqlServerSeed();
  const msPath = join(ROOT_DIR, "init/sqlserver/02_seed_data.sql");
  writeFileSync(msPath, msSql, "utf-8");
  console.log(`  ✓ ${msPath} (${(msSql.length / 1024 / 1024).toFixed(1)} MB)\n`);

  console.log("3/3 MySQL (iomadprod)...");
  const mySql = buildMySQLSeed();
  const myPath = join(ROOT_DIR, "init/mysql/02_seed_data.sql");
  writeFileSync(myPath, mySql, "utf-8");
  console.log(`  ✓ ${myPath} (${(mySql.length / 1024 / 1024).toFixed(1)} MB)\n`);

  console.log("✅ All 3 SQL seed files generated!");
}

main();
